kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cephfs-provisioner
  labels:
    app.kubernetes.io/name: {{ include "cephfs-provisioner.fullname" . }}
    helm.sh/chart: {{ include "cephfs-provisioner.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cephfs-provisioner.fullname" . }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "cephfs-provisioner.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
