apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cephfs-provisioner.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "cephfs-provisioner.fullname" . }}
    helm.sh/chart: {{ include "cephfs-provisioner.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "delete"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
