apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cephfs-provisioner.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "cephfs-provisioner.fullname" . }}
    helm.sh/chart: {{ include "cephfs-provisioner.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
